// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Match Next.js precedence: .env.local wins over .env. `vercel env pull` writes
// the real (Neon) DATABASE_URL to .env.local, while .env still carries the dead
// pre-Postgres `file:./dev.db`. Bare `dotenv/config` reads only .env and would
// therefore point every CLI migration at a database that no longer exists.
// dotenv keeps the first value it sees, so .env.local must come first.
config({ path: [".env.local", ".env"] });

// Migrations must run over Neon's DIRECT endpoint, not the pooled one.
// `prisma migrate` guards itself with a session-level advisory lock
// (pg_advisory_lock), and a session lock taken through PgBouncer is not
// reliably held by — or released from — the same backend that took it. Through
// the pooled URL this fails as `P1002: timed out trying to acquire a postgres
// advisory lock`, which is what broke the first production build.
//
// This file configures only the Prisma CLI. The running app still connects via
// the pooled DATABASE_URL in src/lib/db.ts, which is what a serverless app
// wants. The fallback keeps non-Neon setups (a plain local Postgres) working.
const migrationUrl =
  process.env["DATABASE_URL_UNPOOLED"] ??
  process.env["POSTGRES_URL_NON_POOLING"] ??
  process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: migrationUrl,
  },
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
});
